---
name: Autossh
version: 1.2.0
slug: autossh
description: Automatically connect to a ssh server for forwarding ports
url: https://github.com/xchwarze/addon-autossh
arch:
  - armv7
  - armhf
  - amd64
  - aarch64
  - i386
advanced: true
startup: application
boot: auto
host_network: true
map:
- share:rw
options:
  hostname: ''
  ssh_port: 22
  username: autossh
  remote_forwarding:
    - 127.0.0.1:8123:172.17.0.1:8123
  local_forwarding:
    - ''
  other_ssh_options: "-v"
  monitor_port: 0
  server_alive_interval: 30
  server_alive_count_max: 3
  gatetime: 0
  retry_interval: 3
  ssh_key_name: addon_autossh_key
  use_share_folder: true
  log_level: info
schema:
  hostname: str
  ssh_port: int(1,65535)
  username: str
  remote_forwarding:
    - str
  local_forwarding:
    - str
  other_ssh_options: str
  monitor_port: int(0,65535)
  server_alive_interval: int
  server_alive_count_max: int
  gatetime: int
  retry_interval: int
  ssh_key_name: str
  use_share_folder: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)
